name: Docker Build and Push

on:
  push:
    branches:
      - docker-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: docker login --username ${{ secrets.USER_NAME }} --password ${{ secrets.TOKEN }}

    - name: Building Docker image
      run: docker build -t ${{ secrets.USER_NAME }}/myimage .

    - name: Pushing to Docker Hub
      run: docker push ${{ secrets.USERNAME }}/myimage
