name: Docker Build and Push

on:
  push:
    branches:
      - docker-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USER_NAME}}
        password: ${{ secrets.TOKEN}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
 